source 'https://rubygems.org'

gem 'awesome_print'
gem 'colorator'
#gem 'git'
gem 'github-markup'
gem 'jekyll'
gem 'jekyll-sitemap'
gem 'liquid'
gem 'liquid-c'
gem 'mercurial-ruby'
gem 'nokogiri'
gem 'pandoc-ruby'
gem 'pygments.rb'
gem 'redcarpet'
gem 'rugged'
gem 'typhoeus'
