source 'https://rubygems.org'

gem 'awesome_print'
gem 'colorator'
#gem 'git'
gem 'github-markup'
gem 'jekyll'
gem 'jekyll-optional-front-matter'
gem 'jekyll-readme-index'
gem 'jekyll-relative-links'
gem 'jekyll-sitemap'
gem 'jekyll-titles-from-headings'
gem 'liquid'#, '~> 2.6.2'
gem 'mercurial-ruby'
gem 'nokogiri'
gem 'pandoc-ruby'
gem 'pygments.rb'
gem 'redcarpet'
gem 'rugged'
gem 'typhoeus'
